version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_alkemy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017